# Generated by Django 3.0.5 on 2020-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_content',
            name='title',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
