# Generated by Django 3.0.5 on 2020-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200423_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_content',
            name='Section1_title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about_content',
            name='Section2_title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about_content',
            name='Section3_title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
