# Generated by Django 3.0.5 on 2020-04-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200423_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_content',
            old_name='Section1_title',
            new_name='title',
        ),
    ]
