# Generated by Django 3.0.5 on 2020-04-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200423_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_content',
            old_name='Section1_Description',
            new_name='description_one',
        ),
        migrations.RenameField(
            model_name='about_content',
            old_name='Section2_Description',
            new_name='description_two',
        ),
        migrations.RenameField(
            model_name='about_content',
            old_name='Section2_title',
            new_name='title_one',
        ),
        migrations.RenameField(
            model_name='about_content',
            old_name='title',
            new_name='title_two',
        ),
    ]
