# Generated by Django 3.0.5 on 2020-04-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200423_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_content',
            old_name='Section3_Description',
            new_name='description_three',
        ),
        migrations.RenameField(
            model_name='about_content',
            old_name='Section3_title',
            new_name='title_three',
        ),
    ]
