# Generated by Django 3.0.5 on 2020-04-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200423_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_content',
            old_name='description_one',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about_content',
            old_name='title_one',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='title_three',
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='title_two',
        ),
    ]
