# Generated by Django 3.0.5 on 2020-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200423_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_content',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
