# Generated by Django 3.0.5 on 2020-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200423_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_content',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
