# Generated by Django 3.0.5 on 2020-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200423_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_content',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_content',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio_content',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
