# Generated by Django 3.0.5 on 2020-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200423_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_content',
            name='bio',
            field=models.TextField(max_length=105),
        ),
    ]
