# Generated by Django 3.0.5 on 2020-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200423_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_work_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio_content',
            name='bio',
            field=models.TextField(max_length=300),
        ),
    ]
