# Generated by Django 3.0.5 on 2020-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200423_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
