# Generated by Django 3.0.5 on 2020-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_portfolio_content_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
