# Generated by Django 3.0.5 on 2020-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_home_content_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_work_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img/work'),
        ),
        migrations.AddField(
            model_name='service_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img/service'),
        ),
        migrations.AlterField(
            model_name='home_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img/home'),
        ),
        migrations.AlterField(
            model_name='portfolio_content',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img/portfolio'),
        ),
    ]
