# Generated by Django 3.0.5 on 2020-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200424_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome_logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('pic', models.ImageField(null=True, upload_to='static/img/logo')),
                ('welcome_text', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
