# Generated by Django 3.0.5 on 2020-04-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_welcome_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome_logo',
            old_name='welcome_text',
            new_name='welocomeText',
        ),
    ]
