# Generated by Django 3.0.5 on 2020-04-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200424_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome_logo',
            old_name='welocomeText',
            new_name='welcomeText',
        ),
    ]
