# Generated by Django 3.0.5 on 2020-04-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200425_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='welcome_logo',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='welcomeText',
            new_name='welcome',
        ),
    ]
