# Generated by Django 3.0.5 on 2020-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200425_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_content',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
