# Generated by Django 3.0.5 on 2020-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20200426_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_content',
            name='section_two_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home_content',
            name='section_two_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
