# Generated by Django 3.0.5 on 2020-04-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200426_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_content',
            old_name='section_two_description',
            new_name='sectionDescription',
        ),
        migrations.RenameField(
            model_name='home_content',
            old_name='section_two_title',
            new_name='sectionTitle',
        ),
    ]
