# Generated by Django 3.0.5 on 2020-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200426_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_content',
            name='pic',
            field=models.ImageField(upload_to='static/img/home'),
        ),
    ]
