# Generated by Django 3.0.5 on 2020-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20200426_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_work_content',
            name='pic',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
