# Generated by Django 3.0.5 on 2020-05-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20200513_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_content',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='service_content',
            name='pic',
        ),
    ]
