# Generated by Django 3.0.5 on 2020-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_portfolio_content_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
