# Generated by Django 3.0.5 on 2020-05-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20200521_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='reference',
        ),
    ]
