# Generated by Django 3.0.5 on 2020-05-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20200521_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reference',
        ),
    ]
