# Generated by Django 3.0.5 on 2020-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_delete_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('file', models.FileField(upload_to='static/references')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
