# Generated by Django 3.0.5 on 2020-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20200521_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
